// <auto-generated />
using Hierarchy.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hierarchy.Storage.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Hierarchy.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<HierarchyId>("HierarchyId")
                        .IsRequired()
                        .HasColumnType("hierarchyid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<HierarchyId>("OldHierarchyId")
                        .HasColumnType("hierarchyid");

                    b.HasKey("Id");

                    b.HasIndex("HierarchyId")
                        .IsUnique();

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HierarchyId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/"),
                            Name = "Lidia Brewer"
                        },
                        new
                        {
                            Id = 2,
                            HierarchyId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/2/"),
                            Name = "Hannah Wicks"
                        },
                        new
                        {
                            Id = 3,
                            HierarchyId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/1/"),
                            Name = "Sheridan Perkins"
                        },
                        new
                        {
                            Id = 4,
                            HierarchyId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/2/"),
                            Name = "Zakaria Bailey"
                        },
                        new
                        {
                            Id = 5,
                            HierarchyId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/2/1/"),
                            Name = "Albert Woodward"
                        },
                        new
                        {
                            Id = 6,
                            HierarchyId = Microsoft.EntityFrameworkCore.HierarchyId.Parse("/1/2/2/"),
                            Name = "Arron Mcdaniel"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
